### PR TITLE
Update Dockerfile.gpu to Handle Node.js Repository Setup Securely. - …

### PR DESCRIPTION
**Pull request by NickThompson42**
…Replaced deprecated Node.js setup script with direct repository addition. - Added GPG key handling for Node.js repository to ensure secure package installations. - Retained all necessary symlinks and permissions to maintain functionality. - Updated

added 607 packages, and audited 608 packages in 26s

41 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (8 moderate, 11 high)

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details. and rebuilt dependencies successfully to ensure dependencies are properly installed. This update prevents deprecation warnings and ensures future compatibility.

### CODE REVIEW

**Comment by pierotofy** [comment]
I don't understand what problem this is solving. Was AI used to generate this?

**Comment by NickThompson42** [comment]
Yeah, sorry I was running through fixes really fast with some AI help. :) I curated, reviewed, and tested this code and it is working on my machine.

I was running into a problem with the `minimist` module and also some issues with `/var/www` permissions and I think they were tied together. The error was:

"""
Error: Cannot find module 'minimist'
Require stack:
- /var/www/config.js
- /var/www/index.js
"""

When I looked at the Docker.gpu file I saw that the `nodesource.com/setup_14.x` was probably throwing warnings during the build process. I thought a 14.x might be a versioning issue with installing `minimist` or other dependencies. So, I worked through how to make it more stable against versioning.

The changes worked on my Ubuntu 22.04.4 LTS. So, I don't know if it's needed for everyone but it worked for me.

- These lines added the Node.js GPG key to add a layer of security.
- Sets up Node.js repo manually. 
- There were some deprecation warnings during the build and this appears to have addressed those too.

---
I replaced:
RUN curl --silent --location https://deb.nodesource.com/setup_14.x | bash -

With this:
RUN curl -fsSL https://deb/nodesource.com/gpgkey/nodesource.gpg.key | gpg--dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install -y nodejs unzip p7zip-full && npm install -g nodemon \
ln -s /code/SuperBuild/install/bin/untwine /usr/bin/untwine && \
ln -s /code/SuperBuild/install/bin/entwine /usr/bin/entwine && \
ln -s /code/SuperBuild/install/bin/pdal /usr/bin/pdal

This resolved the problem on my end, but I'm open to any feedback. Thanks for taking a look!

**Comment by pierotofy** [comment]
It's strange you were having issues with permissions and minimist, but I don't think changing the installation source of node is the root cause.

I'm not against the use of co-pilots, but please don't use AI to generate future entire pull requests 🙏
